apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-1
  name: nginx-1
  namespace: default 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:  
      - name: nginx-1
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /index1.html
            name: nginx-vol
            subPath: index1.html
      volumes:
        - configMap:
            defaultMode: 0777
            name: index1
            items:
              - key: index1.html
                path: index1.html
          name: index1-vol


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index1
data:
  index1.html: |
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Maximized Image</title>
  <style>
    html, body {
      margin: 0;
      padding: 0;
      height: 100%;
    }
    #image-container {
      width: 100%;
      height: 100%;
      position: absolute;
      top: 0;
      left: 0;
      overflow: hidden;
    }
    #image-container img {
      width: 100%;
      height: auto;
      display: block;
    }
  </style>
</head>
<body>
  <div id="image-container">
    <img src="your-image.jpg" alt="Maximized Image">
  </div>
</body>
</html>
