apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-1
  name: nginx-1
  namespace: default 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:  
      - name: nginx-1
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /usr/share/nginx/html/index1.html
            name: nginx-vol
            subPath: index1.html
      volumes:
        - configMap:
            defaultMode: 0777
            name: index1
            items:
              - key: index1.html
                path: index1.html
          name: nginx-vol


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index1
data:
  index1.html: |
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Timestamp</title>
  <style>
    .hidden {
      display: none;
    }
  </style>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="refresh" content="5">
  <title>Maximized Image</title>
  <style>
    html, body {
      margin: 0;
      padding: 0;
      height: 100%;
    }
    #image-container {
      width: 100%;
      height: 100%;
      position: absolute;
      top: 0;
      left: 0;
      overflow: hidden;
    }
    #image-container img {
      width: 100%;
      height: auto;
      display: block;
    }
  </style>
</head>
<body>
  <p id="timestamp" class="hidden"></p>

  <script>
    // Generate timestamp
    function generateTimestamp() {
      var date = new Date();
      return date.toISOString();
    }

    // Display timestamp in the hidden element
    function displayTimestamp() {
      var timestampElement = document.getElementById("timestamp");
      timestampElement.textContent = generateTimestamp();
      timestampElement.classList.remove("hidden");
    }

    // Call the displayTimestamp function
    displayTimestamp();
  </script>

  <div id="image-container">
    <img src="data:image/jpeg;base64,<base64-encoded-image-data>" alt="Embedded Image">
  </div>
</body>
</html>
