apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-udev-drm
spec:
  brokerProperties: {}
  brokerSpec:
    brokerPodSpec:
      containers:
        - name: display
          env:
            - name: URL
              value: http://diablo.seader.us
            - name: DISPLAY
              value: ':0'
          image: registry.opensuse.org/home/atgracey/wallboardos/15.4/firefox:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /home/user/
              name: home
            - mountPath: /root/
              name: home
        - name: x11
          image: registry.opensuse.org/home/atgracey/wallboardos/15.4/x11:icewm
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /root
              name: home
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 5
      volumes:
        - name: tmp
          emptyDir: {}
        - name: home
          emptyDir: {}
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      udevRules:
      - SUBSYSTEM=="drm", KERNEL=="card0-HDMI-A-1"
    name: udev
